CREATE DATABASE IF NOT EXISTS social_network

DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT ,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(100) NOT NULL,
    avatar VARCHAR(200), 
    is_admin BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id),
) ENGINE=InnoDB CHARSET=utf8mb4